// <auto-generated />
using DateMe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DateMe.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20220127035531_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("DateMe.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Comedy",
                            DirectorFirstName = "Richard",
                            DirectorLastName = "Curtis",
                            Edited = true,
                            LentTo = "",
                            Notes = "Merry Christmas!",
                            Rating = "R",
                            Title = "Love Actually",
                            Year = (ushort)2003
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "War/Drama",
                            DirectorFirstName = "Ridley",
                            DirectorLastName = "Scott",
                            Edited = false,
                            LentTo = "",
                            Notes = "MUST: Director's Cut",
                            Rating = "R",
                            Title = "Kingdom of Heaven",
                            Year = (ushort)2005
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Thriller/Crime",
                            DirectorFirstName = "Hoon-jung",
                            DirectorLastName = "Park",
                            Edited = false,
                            LentTo = "",
                            Notes = "BEST EVER",
                            Rating = "R",
                            Title = "New World",
                            Year = (ushort)2013
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
